### ISSUE TITLE
Taro@3.0.5 编译成头条小程序，使用最新的1.70.X的基础库报错

### ISSUE THREAD

**Issue by Naico** [NervJS/taro#7121] opened 2020-07-21 06:43 UTC
![image](https://user-images.githubusercontent.com/2639245/88021668-8660a100-cb60-11ea-89b9-5b9e0b386886.png)

**Comment by Naico** [comment] 2020-07-21 06:44
![image](https://user-images.githubusercontent.com/2639245/88021782-adb76e00-cb60-11ea-9988-b126e9411d24.png)

**Comment by Chen-jj** [comment] 2020-07-21 11:33
duplicate of #6929

**Closed by Chen-jj** 2020-07-21 11:33 UTC
Labels: duplicate
