### ISSUE TITLE
H5 报错 Cannot read properties of undefined (reading 'list')

### ISSUE THREAD

**Issue by LovesLolita** [NervJS/taro#13654] opened 2023-04-13 15:36 UTC
### 相关平台
H5

### 复现仓库
[https://github.com/LovesLolita/jiangs-blog-mini-taro.git](https://github.com/LovesLolita/jiangs-blog-mini-taro.git)
**浏览器版本: chrome**
**使用框架: React**

### 复现步骤
启动项目首页就报错,但是微信小程序没有问题

### 期望结果
求求了 告知一下原因

### 实际结果
求告知问题

### 环境信息
```
Taro CLI 3.6.4 environment info:
    System:
      OS: macOS 13.2.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 14.21.3 - ~/.nvm/versions/node/v14.21.3/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v14.21.3/bin/yarn
      npm: 6.14.18 - ~/.nvm/versions/node/v14.21.3/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.4 => 3.6.4 
      @tarojs/components: 3.6.4 => 3.6.4 
      @tarojs/helper: 3.6.4 => 3.6.4 
      @tarojs/plugin-framework-react: 3.6.4 => 3.6.4 
      @tarojs/plugin-html: ^3.6.4 => 3.6.4 
      @tarojs/plugin-platform-alipay: 3.6.4 => 3.6.4 
      @tarojs/plugin-platform-h5: 3.6.4 => 3.6.4 
      @tarojs/plugin-platform-jd: 3.6.4 => 3.6.4 
      @tarojs/plugin-platform-qq: 3.6.4 => 3.6.4 
      @tarojs/plugin-platform-swan: 3.6.4 => 3.6.4 
      @tarojs/plugin-platform-tt: 3.6.4 => 3.6.4 
      @tarojs/plugin-platform-weapp: 3.6.4 => 3.6.4 
      @tarojs/react: 3.6.4 => 3.6.4 
      @tarojs/runtime: 3.6.4 => 3.6.4 
      @tarojs/shared: 3.6.4 => 3.6.4 
      @tarojs/taro: 3.6.4 => 3.6.4 
      @tarojs/webpack5-runner: 3.6.4 => 3.6.4 
      babel-preset-taro: 3.6.4 => 3.6.4 
      eslint-config-taro: 3.6.4 => 3.6.4 
      react: ^18.0.0 => 18.2.0 
```

---
### 补充信息
vendors-node_modules_taro_h5_prebundle_chunk-PT22VGQK_js.js:28308 Uncaught TypeError: Cannot read properties of undefined (reading 'list')
    at new push../node_modules/.taro/h5/prebundle/chunk-PT22VGQK.js.proxyCustomElement.conf (vendors-node_modules_taro_h5_prebundle_chunk-PT22VGQK_js.js:28308:32)
    at initTabbar (vendors-node_modules_taro_h5_prebundle_chunk-PT22VGQK_js.js:30032:29)
    at PageHandler.mount (vendors-node_modules_taro_h5_prebundle_chunk-PT22VGQK_js.js:6224:13)
    at new PageHandler (vendors-node_modules_taro_h5_prebundle_chunk-PT22VGQK_js.js:6377:14)
    at createRouter (vendors-node_modules_taro_h5_prebundle_chunk-PT22VGQK_js.js:6413:21)
    at eval (app.boot.js?b851:71:1)
    at ./src/app.boot.js (src_app_boot_js.js:381:1)
    at options.factory (runtime.js:815:31)
    at __webpack_require__ (runtime.js:36:33)
    at Function.fn (runtime.js:486:21)

**Comment by yoyo837** [comment] 2023-04-14 01:51
问题应该出在 tabBar 有关的地方,  可以先看看 https://github.com/NervJS/taro/issues/7302 是否有帮助.

**Comment by ZakaryCode** [comment] 2023-04-14 02:10
Duplicate of #13581

**Closed** 2023-04-14 07:10 UTC
Labels: T-h5
