### ISSUE TITLE
npm run dev:weapp 报错

### ISSUE THREAD

**Issue by dwg520** [NervJS/taro#13556] opened 2023-04-02 15:20 UTC
### 相关平台
微信小程序

### 复现仓库
[https://github.com/dwg520/myApp.git](https://github.com/dwg520/myApp.git)
**小程序基础库: 1.0.0**
**使用框架: Vue 3**

### 复现步骤
1.vue3.0
2.使用ts
3.预处理器sass
4.打包工具webpack4.0
5.包管理工具npm
 npm run dev:weapp

> myApp@1.0.0 dev:weapp
> npm run build:weapp -- --watch

> myApp@1.0.0 build:weapp
> taro build --type weapp "--watch"

👽 Taro v3.6.2

Tips:
1. 预览模式生成的文件较大，设置 NODE_ENV 为 production 可以开启压缩。
Example:
$ set NODE_ENV=production && taro build --type weapp --watch
缺少 app 全局配置文件，请检查！
缺少 app 全局配置文件，请检查！

node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

Error: 缺少 app 全局配置文件，请检查！
    at TaroMiniPlugin.getAppConfig (D:\taro\myApp\node_modules\@tarojs\mini-runner\src\plugins\MiniPlugin.ts:527:13)
    at TaroMiniPlugin.run (D:\taro\myApp\node_modules\@tarojs\mini-runner\src\plugins\MiniPlugin.ts:397:29)
    at TaroMiniPlugin.<anonymous> (D:\taro\myApp\node_modules\@tarojs\mini-runner\src\plugins\MiniPlugin.ts:211:20)
    at Generator.next (<anonymous>)
    at D:\taro\myApp\node_modules\@tarojs\mini-runner\dist\plugins\MiniPlugin.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (D:\taro\myApp\node_modules\@tarojs\mini-runner\dist\plugins\MiniPlugin.js:4:12)
    at D:\taro\myApp\node_modules\@tarojs\mini-runner\src\plugins\MiniPlugin.ts:206:58
    at TaroMiniPlugin.<anonymous> (D:\taro\myApp\node_modules\@tarojs\mini-runner\src\plugins\MiniPlugin.ts:166:13)
    at Generator.next (<anonymous>)
    at D:\taro\myApp\node_modules\@tarojs\mini-runner\dist\plugins\MiniPlugin.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (D:\taro\myApp\node_modules\@tarojs\mini-runner\dist\plugins\MiniPlugin.js:4:12)
    at D:\taro\myApp\node_modules\@tarojs\mini-runner\src\plugins\MiniPlugin.ts:164:44
    at AsyncSeriesHook.eval [as callAsync] (eval at create (D:\taro\myApp\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:20:1)
    at AsyncSeriesHook.lazyCompileHook (D:\taro\myApp\node_modules\tapable\lib\Hook.js:154:20)

### 期望结果
运行成功

### 实际结果
 npm run dev:weapp

> myApp@1.0.0 dev:weapp
> npm run build:weapp -- --watch

> myApp@1.0.0 build:weapp
> taro build --type weapp "--watch"

👽 Taro v3.6.2

Tips:
1. 预览模式生成的文件较大，设置 NODE_ENV 为 production 可以开启压缩。
Example:
$ set NODE_ENV=production && taro build --type weapp --watch
缺少 app 全局配置文件，请检查！
缺少 app 全局配置文件，请检查！
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

Error: 缺少 app 全局配置文件，请检查！
    at TaroMiniPlugin.getAppConfig (D:\taro\myApp\node_modules\@tarojs\mini-runner\src\plugins\MiniPlugin.ts:527:13)
    at TaroMiniPlugin.run (D:\taro\myApp\node_modules\@tarojs\mini-runner\src\plugins\MiniPlugin.ts:397:29)
    at TaroMiniPlugin.<anonymous> (D:\taro\myApp\node_modules\@tarojs\mini-runner\src\plugins\MiniPlugin.ts:211:20)
    at Generator.next (<anonymous>)
    at D:\taro\myApp\node_modules\@tarojs\mini-runner\dist\plugins\MiniPlugin.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (D:\taro\myApp\node_modules\@tarojs\mini-runner\dist\plugins\MiniPlugin.js:4:12)
    at D:\taro\myApp\node_modules\@tarojs\mini-runner\src\plugins\MiniPlugin.ts:206:58
    at TaroMiniPlugin.<anonymous> (D:\taro\myApp\node_modules\@tarojs\mini-runner\src\plugins\MiniPlugin.ts:166:13)
    at Generator.next (<anonymous>)
    at D:\taro\myApp\node_modules\@tarojs\mini-runner\dist\plugins\MiniPlugin.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (D:\taro\myApp\node_modules\@tarojs\mini-runner\dist\plugins\MiniPlugin.js:4:12)
    at D:\taro\myApp\node_modules\@tarojs\mini-runner\src\plugins\MiniPlugin.ts:164:44
    at AsyncSeriesHook.eval [as callAsync] (eval at create (D:\taro\myApp\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:20:1)
    at AsyncSeriesHook.lazyCompileHook (D:\taro\myApp\node_modules\tapable\lib\Hook.js:154:20)

### 环境信息
```
👽 Taro v3.6.2


  Taro CLI 3.6.2 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.13.2 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
```

**Comment by yangjisen** [comment] 2023-04-02 16:17
同样的故障+1

**Comment by algaeReed** [comment] 2023-04-02 16:23
me too

**Comment by 303394539** [comment] 2023-04-03 00:28
"@swc/core": "1.3.42"
可以解决

**Comment by dwg520** [comment] 2023-04-03 01:19
> "@swc/core": "1.3.42" 可以解决

试过了   不行

**Comment by xuanzebin** [comment] 2023-04-03 01:47
Duplicate of #13554

**Closed by xuanzebin** 2023-04-03 01:47 UTC
Labels: V-3, F-vue3, T-weapp

**Comment by Melon910** [comment] 2023-04-03 01:48
+1

**Comment by xuanzebin** [comment] 2023-04-03 01:54
Duplicate of #13544

**Comment by AlienwareBoy** [comment] 2023-04-04 09:21
无论我怎么选择，他都是暴这个错误，求解决

**Comment by AlienwareBoy** [comment] 2023-04-04 09:23
{
  "name": "nurse",
  "version": "1.0.0",
  "private": true,
  "description": "nurse",
  "templateInfo": {
    "name": "default",
    "typescript": false,
    "css": "sass"
  },
  "scripts": {
    "build:weapp": "taro build --type weapp",
    "build:swan": "taro build --type swan",
    "build:alipay": "taro build --type alipay",
    "build:tt": "taro build --type tt",
    "build:h5": "taro build --type h5",
    "build:rn": "taro build --type rn",
    "build:qq": "taro build --type qq",
    "build:jd": "taro build --type jd",
    "build:quickapp": "taro build --type quickapp",
    "dev:weapp": "npm run build:weapp -- --watch",
    "dev:swan": "npm run build:swan -- --watch",
    "dev:alipay": "npm run build:alipay -- --watch",
    "dev:tt": "npm run build:tt -- --watch",
    "dev:h5": "npm run build:h5 -- --watch",
    "dev:rn": "npm run build:rn -- --watch",
    "dev:qq": "npm run build:qq -- --watch",
    "dev:jd": "npm run build:jd -- --watch",
    "dev:quickapp": "npm run build:quickapp -- --watch"
  },
  "browserslist": [
    "last 3 versions",
    "Android >= 4.1",
    "ios >= 8"
  ],
  "author": "",
  "dependencies": {
    "@babel/runtime": "^7.7.7",
    "@tarojs/components": "3.5.10",
    "@tarojs/helper": "3.5.10",
    "@tarojs/plugin-framework-vue3": "3.5.10",
    "@tarojs/plugin-platform-alipay": "3.5.10",
    "@tarojs/plugin-platform-jd": "3.5.10",
    "@tarojs/plugin-platform-qq": "3.5.10",
    "@tarojs/plugin-platform-swan": "3.5.10",
    "@tarojs/plugin-platform-tt": "3.5.10",
    "@tarojs/plugin-platform-weapp": "^3.6.3",
    "@tarojs/router": "3.5.10",
    "@tarojs/runtime": "3.5.10",
    "@tarojs/shared": "3.5.10",
    "@tarojs/taro": "3.5.10",
    "@tarojs/taro-h5": "3.5.10",
    "vue": "^3.0.0"
  },
  "devDependencies": {
    "@swc/core": "1.3.42",
    "@babel/core": "^7.8.0",
    "@tarojs/cli": "3.5.10",
    "@tarojs/mini-runner": "3.5.10",
    "@tarojs/webpack-runner": "3.5.10",
    "@types/webpack-env": "^1.13.6",
    "@vue/babel-plugin-jsx": "^1.0.6",
    "@vue/compiler-sfc": "^3.0.0",
    "babel-preset-taro": "3.5.10",
    "css-loader": "3.4.2",
    "eslint": "^8.12.0",
    "eslint-config-taro": "3.5.10",
    "eslint-plugin-vue": "^8.0.0",
    "style-loader": "1.3.0",
    "stylelint": "^14.4.0",
    "vue-loader": "^17.0.0",
    "webpack": "4.46.0"
  }
}
使用的默认模板
ts
sass
vue3

**Comment by yoyo837** [comment] 2023-04-04 09:27
@AlienwareBoy 锁一下版本

**Comment by yoyo837** [comment] 2023-04-04 09:33
npm ls一下看看

**Comment by AlienwareBoy** [comment] 2023-04-04 09:39
<img width="506" alt="image" src="https://user-images.githubusercontent.com/25809878/229752216-69399a30-d49b-4c3c-847b-37fec3839288.png">
@yoyo837

**Comment by AlienwareBoy** [comment] 2023-04-04 09:40
当我安装的时候，出现了Cannot find module 'vue/compiler-sfc'的报错，然后我将vue-loader的版本降到了@15,但是还是会有一些错误

**Comment by yoyo837** [comment] 2023-04-04 09:53
`npm ls @swc/core`, 我以为你理解我的意思.

**Comment by AlienwareBoy** [comment] 2023-04-04 09:58
不好意思，我理解错误了
<img width="473" alt="image" src="https://user-images.githubusercontent.com/25809878/229757183-1402f4c2-ba87-4407-b115-e16e1a67e741.png">

**Comment by yoyo837** [comment] 2023-04-04 09:59
所以, 锁一下1.3.42试一试

**Comment by AlienwareBoy** [comment] 2023-04-04 10:06
<img width="619" alt="image" src="https://user-images.githubusercontent.com/25809878/229758763-4db688a4-bfd6-43ed-bdc7-67a88eaf0e8b.png">
@yoyo837 你好，其中我使用了1.3.42,1.3.45这两个版本进行试验，都还是这个错误，我在"@swc/core": "1.3.42", 没有加上了^这个符号，这个算锁版本了么

**Comment by yoyo837** [comment] 2023-04-04 10:08
https://github.com/NervJS/taro/issues/13544#issuecomment-1491488805

**Comment by AlienwareBoy** [comment] 2023-04-04 10:17
@yoyo837 你好，谢谢你，问题已经解决了，我这样写入就行了
package.json

{
"resolutions": {
    "@swc/core": "1.3.42"
  },
  "dependencies": {
    "@swc/core": "1.3.42",
  }
}

  如果单纯删除yarn.lock 或者是npm  的 packjson.lock 还不行，要向上面那样写入

**Comment by SpringHgui** [comment] 2023-04-21 09:09
直接初始化新项目，编译就报这个错

**Comment by itcatplayit** [comment] 2023-09-06 09:57
> 当我安装的时候，出现了Cannot find module 'vue/compiler-sfc'的报错，然后我将vue-loader的版本降到了@15,但是还是会有一些错误

我也出现这个报错，我是将 vue-loader 升级到最新版重新安装依赖就跑通了。【"vue-loader": "^17.2.2"】
