### ISSUE TITLE
[RN]Taro.showActionSheet使用报错

### ISSUE THREAD

**Issue by tourze** [NervJS/taro#3802] opened 2019-07-12 10:59 UTC
**问题描述**
在RN下hen很简单地使用Taro.showActionSheet，然后报错，但是action sheet是出来了

![image](https://user-images.githubusercontent.com/13899502/61123446-f14fb480-a4d6-11e9-98f9-4a55ecba3032.png)

**期望行为**
没报错信息

**系统信息**
👽 Taro v1.3.8

  Taro CLI 1.3.8 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.9.0 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: 1.3.8 => 1.3.8 
      @tarojs/cli: 1.3.8 => 1.3.8 
      @tarojs/components: 1.3.8 => 1.3.8 
      @tarojs/components-rn: 1.3.8 => 1.3.8 
      @tarojs/plugin-babel: 1.3.8 => 1.3.8 
      @tarojs/plugin-csso: 1.3.8 => 1.3.8 
      @tarojs/plugin-sass: 1.3.8 => 1.3.8 
      @tarojs/plugin-uglifyjs: 1.3.8 => 1.3.8 
      @tarojs/redux: 1.3.8 => 1.3.8 
      @tarojs/redux-h5: 1.3.8 => 1.3.8 
      @tarojs/rn-runner: 1.3.8 => 1.3.8 
      @tarojs/router: 1.3.8 => 1.3.8 
      @tarojs/taro: 1.3.8 => 1.3.8 
      @tarojs/taro-alipay: 1.3.8 => 1.3.8 
      @tarojs/taro-h5: 1.3.8 => 1.3.8 
      @tarojs/taro-redux-rn: 1.3.8 => 1.3.8 
      @tarojs/taro-rn: 1.3.8 => 1.3.8 
      @tarojs/taro-router-rn: 1.3.8 => 1.3.8 
      @tarojs/taro-swan: 1.3.8 => 1.3.8 
      @tarojs/taro-tt: 1.3.8 => 1.3.8 
      @tarojs/taro-weapp: 1.3.8 => 1.3.8 
      @tarojs/webpack-runner: 1.3.8 => 1.3.8 
      eslint-config-taro: 1.3.8 => 1.3.8 
      eslint-plugin-taro: 1.3.8 => 1.3.8 
      nerv-devtools: ^1.4.1 => 1.4.1 
      nervjs: ^1.3.0 => 1.3.9 
      react: 16.3.1 => 16.3.1 
      react-native: 0.55.4 => 0.55.4 
    npmGlobalPackages:
      typescript: 2.4.2

**Comment by Pines-Cheng** [comment] 2019-07-23 08:42
duplicate of #3113

**Closed by Pines-Cheng** 2019-07-23 08:42 UTC
Labels: React Native
