### ISSUE TITLE
nom run dev:h5 报错

### ISSUE THREAD

**Issue by juvham** [NervJS/taro#90] opened 2018-06-12 09:37 UTC
监听文件修改中...

events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 0.0.0.0:8080
    at Server.setupListenHandle [as _listen2] (net.js:1330:14)
    at listenInCluster (net.js:1378:12)
    at doListen (net.js:1491:7)
    at process._tickCallback (internal/process/next_tick.js:174:19)
Emitted 'error' event at:
    at emitErrorNT (net.js:1357:8)
    at process._tickCallback (internal/process/next_tick.js:174:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bbtaroapp@1.0.0 build:h5: `taro build --type h5 "--watch"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bbtaroapp@1.0.0 build:h5 script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jhyi/.npm/_logs/2018-06-12T09_25_15_883Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bbtaroapp@1.0.0 dev:h5: `npm run build:h5 -- --watch`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bbtaroapp@1.0.0 dev:h5 script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jhyi/.npm/_logs/2018-06-12T09_25_15_937Z-debug.log

**Comment by yuche** [comment] 2018-06-12 09:39
Duplicate of #86 

应该是端口被占用了， #86 有解决方案，

**Comment by juvham** [comment] 2018-06-12 10:31
sorry：
 谢谢您的回复。问题解决了

**Closed** 2018-06-12 12:10 UTC
