### ISSUE TITLE
在taro的函数式组件中使用@tarojs/redux的useSelector报错

### ISSUE THREAD

**Issue by sansx** [NervJS/taro#3683] opened 2019-07-05 03:33 UTC
**问题描述**
在taro的函数式组件中使用@tarojs/redux的useSelector报错

**复现步骤**
~~1. 安装依赖~~
~~2. 直接运行`yarn dev:h5`~~
~~3. 报错文件为`demo\src\component\Test.tsx`~~
~~[demo地址](https://github.com/sansx/taro-demo)~~
已知错误：为[文档](https://nervjs.github.io/taro/docs/redux.html#useselector)中出现，但是未实现的方法

**期望行为**
正常编译

**报错信息**
" '@tarojs/redux-h5' does not contain an export named 'useSelector'.

**系统信息**
👽 Taro v1.3.4

  Taro CLI 1.3.4 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.12.0 - /usr/local/bin/node
      Yarn: 1.16.0 - ~/.npm-global/lib/node_modules/yarn/bin/yarn
      npm: 6.8.0 - ~/.npm-global/bin/npm
    npmPackages:
      @tarojs/components: 1.3.4 => 1.3.4 
      @tarojs/plugin-babel: 1.3.4 => 1.3.4 
      @tarojs/plugin-csso: 1.3.4 => 1.3.4 
      @tarojs/plugin-stylus: 1.3.4 => 1.3.4 
      @tarojs/plugin-uglifyjs: 1.3.4 => 1.3.4 
      @tarojs/redux: ^1.3.5 => 1.3.5 
      @tarojs/redux-h5: ^1.3.5 => 1.3.5 
      @tarojs/router: 1.3.4 => 1.3.4 
      @tarojs/taro: 1.3.4 => 1.3.4 
      @tarojs/taro-alipay: 1.3.4 => 1.3.4 
      @tarojs/taro-h5: 1.3.4 => 1.3.4 
      @tarojs/taro-swan: 1.3.4 => 1.3.4 
      @tarojs/taro-tt: 1.3.4 => 1.3.4 
      @tarojs/taro-weapp: 1.3.4 => 1.3.4 
      @tarojs/webpack-runner: 1.3.4 => 1.3.4 
      eslint-config-taro: 1.3.4 => 1.3.4 
      eslint-plugin-taro: 1.3.4 => 1.3.4 
      nerv-devtools: ^1.4.0 => 1.4.3 
      nervjs: ^1.4.0 => 1.4.3 
    npmGlobalPackages:
      typescript: 3.5.2

**Comment by loveonelong** [comment] 2019-07-05 05:39
#3447

**Comment by sansx** [comment] 2019-07-05 06:42
根据#3447 的方法
1. 到`node_modules/@tarojs/redux-h5`，安装最新的`nerv-redux`，无效
2. 删除`node_modules`，以及项目根目录的`yarn.lock`文件，无效
3. 在做完第二步之后，重新第一步，查看`@tarojs/redux-h5`的`package.json`相关部分为：
```
"peerDependencies": {
    "nervjs": "^1.4.0",
    "redux": "^2.0.0 || ^3.0.0 || ^4.0.0-0"
  },
  "dependencies": {
    "hoist-non-react-statics": "^2.5.0",
    "invariant": "^2.2.4",
    "loose-envify": "^1.1.0",
    "nerv-redux": "^1.4.3",
    "prop-types": "^15.6.1"
  },
```
同样无效，将`nerv-redux`版本安装为`1.4.1`，依旧报错

**Comment by loveonelong** [comment] 2019-07-05 07:42
https://github.com/NervJS/taro/issues/3447#issuecomment-502678784

**Comment by sansx** [comment] 2019-07-05 07:55
好吧，谢谢，看之前的回答还以为有解决方法，毕竟文档里面写着能用，实际却报错还是挺尴尬的，那这个功能有预计什么时候能有吗，看之前的issue已经提了有半个月多了

**Comment by loveonelong** [comment] 2019-07-05 08:01
@Littly 同问

**Comment by yuche** [comment] 2019-07-15 06:35
Duplicate of #3447

**Closed by yuche** 2019-07-15 06:35 UTC
Labels: Redux
