### ISSUE TITLE
[Taro3]页面采用函数组件配合redux，react会报错

### ISSUE THREAD

**Issue by myl0204** [NervJS/taro#6991] opened 2020-07-10 02:18 UTC
### 相关平台
微信小程序

### 复现仓库
[https://github.com/myl0204/taro_bug_report](https://github.com/myl0204/taro_bug_report)
**小程序基础库: 2.10.1**
**使用框架: React**

### 复现步骤
启动项目后可以在控制台看到报错

VM67:1 Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?%s%s 

Check the render method of `ConnectFunction`. 
    in Index (created by ConnectFunction)
    in ConnectFunction (created by Page)
    in root (created by Page)
    in Page (created by AppWrapper)
    in Provider (created by App)
    in App (created by AppWrapper)
    in AppWrapper

### 期望结果
不报错

### 实际结果
报错

### 环境信息
```
Taro CLI 3.0.2 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.16.3 - /var/folders/_3/wg3rh3_n0hg717bgfzcy8rmw0000gp/T/yarn--1594347472808-0.27392778454151534/node
      Yarn: 1.22.4 - /var/folders/_3/wg3rh3_n0hg717bgfzcy8rmw0000gp/T/yarn--1594347472808-0.27392778454151534/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v10.16.3/bin/npm
    npmPackages:
      @tarojs/cli: ^3.0.2 => 3.0.2
      @tarojs/components: 3.0.2 => 3.0.2
      @tarojs/mini-runner: 3.0.2 => 3.0.2
      @tarojs/react: 3.0.2 => 3.0.2
      @tarojs/runtime: 3.0.2 => 3.0.2
      @tarojs/taro: 3.0.2 => 3.0.2
      @tarojs/webpack-runner: 3.0.2 => 3.0.2
      babel-preset-taro: 3.0.2 => 3.0.2
      eslint-config-taro: 3.0.2 => 3.0.2
      react: ^16.10.0 => 16.13.1
```

**Comment by Chen-jj** [comment] 2020-07-17 05:41
duplicate of #6980

**Closed by Chen-jj** 2020-07-17 05:41 UTC
Labels: F-react, T-weapp, V-3, duplicate
