### ISSUE TITLE
微信小程序自定义组件事件阻止冒泡失败

### ISSUE THREAD

**Issue by qianzhaoy** [NervJS/taro#2553] opened 2019-03-22 06:11 UTC
编译后代码截图: 
![image](https://user-images.githubusercontent.com/14267409/54803773-d9e08780-4cab-11e9-8da0-78b4eed152bf.png)

编译前代码: 
![image](https://user-images.githubusercontent.com/14267409/54803864-36dc3d80-4cac-11e9-9603-d2dfd342a713.png)
![image](https://user-images.githubusercontent.com/14267409/54803883-4d829480-4cac-11e9-8292-f4da2265382d.png)

**Comment by yuche** [comment] 2019-03-22 08:40
Duplicate of #761

**Comment by yuche** [comment] 2019-03-22 08:40
看这个： https://github.com/NervJS/taro/issues/761#issuecomment-472283713

**Closed by yuche** 2019-03-22 08:40 UTC
