### ISSUE TITLE
error: taro-build(1) does not exist, try --help

### ISSUE THREAD

**Issue by hqwlkj** [NervJS/taro#1391] opened 2018-12-06 03:25 UTC
**问题描述**
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]
在项目中执行 ： yarn dev:weapp  或者 npm run dev:weapp 都会出现 `error: taro-build(1) does not exist, try --help` 错误提示。
**复现步骤**
[复现问题的步骤]

[或者可以直接贴源代码，能贴文字就不要截图]

```js
// 这里可以贴代码
npm run dev:weapp 

or 
yarn dev:weapp

```

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]

**报错信息**
> taro build --type weapp "--watch"

👽 Taro v1.2.0-beta.9

error: taro-build(1) does not exist, try --help
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Test@1.0.0 build:weapp: `taro build --type weapp "--watch"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the Test@1.0.0 build:weapp script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/yanghc/.npm/_logs/2018-12-06T03_19_14_036Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Test@1.0.0 dev:weapp: `npm run build:weapp -- --watch`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the Test@1.0.0 dev:weapp script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**系统信息**

 - 操作系统: macOS Mojave
 - Taro 版本 Taro v1.2.0-beta.9
 - Node.js 版本  v10.12.0
 - 报错平台 h5, weapp

**Comment by luckyadam** [comment] 2018-12-06 06:10
换 npm 或者 cnpm 把 cli 再装一下

**Comment by luckyadam** [comment] 2018-12-06 06:12
Duplicate of #699

**Closed by luckyadam** 2018-12-06 06:12 UTC
