### ISSUE TITLE
yarn dev:h5 fail

### ISSUE THREAD

**Issue by kalsolio** [NervJS/taro#241] opened 2018-07-02 01:47 UTC
开始编译项目 myApp2

监听文件修改中...

⠋ Starting development server, please wait🤡~> Listening at http://192.168.232.1:8080/
> Listening at http://localhost:8080/

✖ Compile failed!

[tsl] ERROR
      TS18002: The 'files' list in config file 'tsconfig.json' is empty.

**Comment by kalsolio** [comment] 2018-07-02 02:43
lio@DESKTOP-JF54T4B:/ws/www/myApp2$ webpack --version
4.14.0
lio@DESKTOP-JF54T4B:/ws/www/myApp2$ yarn dev:h5
yarn run v1.7.0
$ npm run build:h5 -- --watch

> myApp2@1.0.0 build:h5 /mnt/e/home/ws/www/myApp2
> taro build --type h5 "--watch"

👽 Taro v0.0.63

开始编译项目 myApp2

监听文件修改中...

⠋ Starting development server, please wait🤡~> Listening at http://192.168.232.1:8080/
> Listening at http://localhost:8080/

✖ Compile failed!

./.temp/app.tsx
Module build failed: Error: You may be using an old version of webpack; please check you're using at least version 4

^C
lio@DESKTOP-JF54T4B:/ws/www/myApp2$ webpack -v
4.14.0

**Comment by kalsolio** [comment] 2018-07-02 02:43
Module build failed: Error: You may be using an old version of webpack; please check you're using at least version 4

^C
lio@DESKTOP-JF54T4B:/ws/www/myApp2$ webpack -v

**Comment by yuche** [comment] 2018-07-05 02:41
Duplicate of #233

**Comment by yuche** [comment] 2018-07-05 02:42
这个问题的进度我们在 #233 追踪处理

**Closed by yuche** 2018-07-05 02:42 UTC
