### ISSUE TITLE
dev:h5 模式下无法编译成功，其他模式如微信小程序模式可以成功。

### ISSUE THREAD

**Issue by estarsyang** [NervJS/taro#5051] opened 2019-12-10 06:18 UTC
### 问题描述
项目初始化，运行 h5模式，无法运行，提示错误。

### 复现步骤

1. taro init xxxx
2. cd xxxx
3. npm run dev:h5
4. throw err

```js


```

### 期望行为
正常运行可预览。

### 报错信息
{ ValidationError: CopyPlugin Invalid Options

options should NOT have fewer than 1 items

    at validateOptions (D:\testCode\rnapp\node_modules\schema-utils\src\validateOptions.js:32:11)
    at new CopyPlugin (D:\testCode\rnapp\node_modules\copy-webpack-plugin\dist\index.js:26:30)
    at init (D:\testCode\rnapp\node_modules\webpack-chain\src\Plugin.js:13:18)
    at Object.toConfig (D:\testCode\rnapp\node_modules\webpack-chain\src\Plugin.js:47:22)
    at clean.Object.assign.plugins.plugins.values.map.plugin (D:\testCode\rnapp\node_modules\webpack-chain\src\Config.js:125:61)
    at Array.map (<anonymous>)
    at module.exports.toConfig (D:\testCode\rnapp\node_modules\webpack-chain\src\Config.js:125:40)
    at Object.<anonymous> (D:\testCode\rnapp\node_modules\@tarojs\webpack-runner\dist\index.js:96:40)
    at Generator.next (<anonymous>)
    at fulfilled (D:\testCode\rnapp\node_modules\@tarojs\webpack-runner\dist\index.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  name: 'ValidationError',
  message:
   'CopyPlugin Invalid Options\n\noptions should NOT have fewer than 1 items\n',
  errors:
   [ { keyword: 'minItems',
       dataPath: '',
       schemaPath: '#/minItems',
       params: [Object],
       message: 'should NOT have fewer than 1 items' } ] }

### 系统信息
👽 Taro v1.3.27

  Taro CLI 1.3.27 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.14.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.17.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD

**Comment by luckyadam** [comment] 2019-12-10 07:09
Duplicate of #5049

**Closed by luckyadam** 2019-12-10 07:09 UTC
Labels: CLI
