### ISSUE TITLE
any tests ?

### ISSUE THREAD

**Issue by zacksleo** [NervJS/taro#64] opened 2018-06-11 05:41 UTC
we need some tests and continuous integrations to make it stronger

**Comment by yuche** [comment] 2018-06-11 05:43
There are some tests in `@tarojs/components`, `@tarojs/eslint-plugin-eslint`, `@tarojs/transformer-wx`, and we are writing more.

**Comment by yuche** [comment] 2018-06-11 17:17
Duplicate of #78

**Closed by yuche** 2018-06-11 17:17 UTC
