### ISSUE TITLE
cli v3.0.0-alpha.6 新建项目后不做任何修改该。直接编译weapp报错

### ISSUE THREAD

**Issue by xgaxpp** [NervJS/taro#5676] opened 2020-03-12 03:49 UTC
#5227 # 问题描述

cli v3.0.0-alpha.6 新建项目后不做任何修改该。直接编译weapp报错,错误信息

编译  发现入口  src/app.ts
编译  发现页面  src/pages/index/index.tsx
| 正在编译...[BABEL] Note: The code generator has deoptimised the styling of D:\workspace\myapp\node_modules\react-reconciler\cjs\react-reconciler.development.js as it exceeds the max of 500KB.
�   编译失败.

./src/app.ts
Module not found: Can't resolve './app.ts"' in 'D:\workspace\myapp\src'

### 复现步骤

1、taro init myapp
2、yarn dev:weapp

### 报错信息

./src/app.ts
Module not found: Can't resolve './app.ts"' in 'D:\workspace\myapp\src'

### 系统信息

Taro CLI 3.0.0-alpha.6 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 13.10.1 - D:\Applications\Scoop\apps\nodejs\current\node.EXE
      Yarn: 1.22.4 - D:\Applications\Scoop\apps\yarn\current\Yarn\bin\yarn.CMD
      npm: 6.13.7 - D:\Applications\Scoop\apps\nodejs\current\npm.CMD

**Comment by yuche** [comment] 2020-03-12 03:52
try alpha.7
Duplicate of #5675

**Closed by yuche** 2020-03-12 03:52 UTC
Labels: CLI
