### ISSUE TITLE
map循环里面调用state数组调用不到

### ISSUE THREAD

**Issue by ShaoGongBra** [NervJS/taro#1298] opened 2018-11-29 06:58 UTC
<View className='main1' hidden={this.state.selectType != 0}>
            {this.state.taboo.map((item, index)=>{
              let remainder = (index) % 12;
              return remainder == 0
                ?<View className={'group group-'+(remainder+1)}>
                  <View className='item item-1 item-max'>
                    <Image src='' className='image' />
                    <Text className='tit'>{item.name}</Text>
                  </View>
                  <View className='right'>
                    {!!this.state.taboo[index+1] && <View className='item item-2 item-min'>
                      <Image src='' className='image' />
                      <Text className='tit'>{this.state.taboo[index+1].name}</Text>
                    </View>}
                    {!!this.state.taboo[index+2] && <View className='item item-3 item-min'>
                      <Image src='' className='image' />
                      <Text className='tit'>{this.state.taboo[index+2].name}</Text>
                    </View>}
                  </View>
                </View>
                :remainder == 3
                ?<View className={'group group-'+(remainder+1)}>
                  <View className='item item-1 item-min'>
                    <Image src='' className='image' />
                    <Text className='tit'>{item.name}</Text>
                  </View>
                  {!!this.state.taboo[index+1] && <View className='item item-2 item-long'>
                      <Image src='' className='image' />
                      <Text className='tit'>{this.state.taboo[index+1].name}</Text>
                    </View>}
                </View>
                :remainder == 5
                ?<View className={'group group-'+(remainder+1)}>
                  <View className='item item-1 item-min'>
                    <Image src='' className='image' />
                    <Text className='tit'>{item.name}</Text>
                  </View>
                  {!!this.state.taboo[index+1] && <View className='item item-2 item-min'>
                    <Image src='' className='image' />
                    <Text className='tit'>{this.state.taboo[index+1].name}</Text>
                  </View>}
                  {!!this.state.taboo[index+2] && <View className='item item-3 item-min'>
                    <Image src='' className='image' />
                    <Text className='tit'>{this.state.taboo[index+2].name}</Text>
                  </View>}
                </View>
                :remainder == 8
                ?<View className={'group group-'+(remainder+1)}>
                  <View className='left'>
                    <View className='item item-1 item-min'>
                      <Image src='' className='image' />
                      <Text className='tit'>{item.name}</Text>
                    </View>
                    {!!this.state.taboo[index+1] && <View className='item item-2 item-min'>
                      <Image src='' className='image' />
                      <Text className='tit'>{this.state.taboo[index+1].name}</Text>
                    </View>}
                  </View>
                  {!!this.state.taboo[index+2] && <View className='item item-3 item-max'>
                    <Image src='' className='image' />
                    <Text className='tit'>{this.state.taboo[index+2].name}</Text>
                  </View>}
                </View>
                :remainder == 11
                ?<View className={'group group-'+(remainder+1)}>
                  <View className='item item-1 item-long-long'>
                    <Image src='' className='image' />
                    <Text className='tit'>{item.name}</Text>
                  </View>
                </View>
                :''
            })}
          </View>

**Comment by yuche** [comment] 2018-11-29 07:47
Duplicate of https://github.com/NervJS/taro/issues/886

**Comment by yuche** [comment] 2018-11-29 07:47
close via https://github.com/NervJS/taro/commit/b3ae01d19d512f90d0927118759631b72b18df20

**Comment by yuche** [comment] 2018-11-29 07:48
能不能装一个 eslint 插件

**Closed by yuche** 2018-11-29 07:47 UTC
