### ISSUE TITLE
 Cannot read property '_$indexKey' of undefine

### ISSUE THREAD

**Issue by thisSillyCow** [NervJS/taro#3544] opened 2019-06-21 03:19 UTC
**问题描述**

数组遍历的时候在 <View> 加 onClick 事件 报错

**复现步骤**

<View className='novelBookFourMutiLine' >
{
	bookList.map((bookInfoItem, index) => {
		return (
			<View className='bookItem' onClick={() => { console.log('1111111') }}></View>
		)
	})
}
</View>

**报错信息**
undefined:4: TypeError: Cannot read property '_$indexKey' of undefined
TypeError: Cannot read property '_$indexKey' of undefined
    at e.dataEOnclickAA (eval at Sn (unknown source), <anonymous>:6570:72)
    at Pi.get (<anonymous>:4:14335)
    at new Pi (<anonymous>:4:14262)
    at qr (<anonymous>:2:19523)
    at Jr (<anonymous>:2:19359)
    at Wr (<anonymous>:2:19302)
    at Dr (<anonymous>:2:18422)
    at Cr (<anonymous>:2:14617)
    at cn (<anonymous>:2:24654)
    at Vr (<anonymous>:2:21468)
com.eclipsesource.v8.V8ScriptExecutionException
	at com.eclipsesource.v8.V8._executeFunction(Native Method)
	at com.eclipsesource.v8.V8.executeFunction(SourceFile:1125)
	at com.eclipsesource.v8.V8Object.executeFunction(SourceFile:370)
	at org.hapjs.render.jsruntime.JsBridgeTimer$a.run(SourceFile:60)
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:207)
	at android.os.HandlerThread.run(HandlerThread.java:61)

**系统信息**
暂时在快应用出现的问题  其他平台没有试过

**补充信息**
不加入 onClick事件不会报错 可能是数组遍历的时候 编译成ux文件导致的

**Comment by yuche** [comment] 2019-06-26 02:14
Duplicate of https://github.com/NervJS/taro/issues/3495

**Comment by yuche** [comment] 2019-06-26 02:14
以后发 issue 只发一个地方就行

**Closed by yuche** 2019-06-26 02:14 UTC
Labels: 快应用

**Comment by thisSillyCow** [comment] 2019-06-26 02:16
哈哈哈 好的 好的 之前不知道啊
